export const PRODUCTS_LIST_REQ = 'PRODUCTS_LIST_REQ';
export const PRODUCTS_LIST_SUCC = 'PRODUCTS_LIST_SUCC';
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL';

export const PRODUCTS_DET_REQ = 'PRODUCTS_DET_REQ';
export const PRODUCTS_DET_SUCC = 'PRODUCTS_DET_SUCC';
export const PRODUCTS_DET_FAIL = 'PRODUCTS_DET_FAIL';

export const PRODUCTS_DELETE_REQ = 'PRODUCTS_DELETE_REQ';
export const PRODUCTS_DELETE_SUCC = 'PRODUCTS_DELETE_SUCC';
export const PRODUCTS_DELETE_FAIL = 'PRODUCTS_DELETE_FAIL';

export const PRODUCTS_CREATE_REQ = 'PRODUCTS_CREATE_REQ';
export const PRODUCTS_CREATE_SUCC = 'PRODUCTS_CREATE_SUCC';
export const PRODUCTS_CREATE_FAIL = 'PRODUCTS_CREATE_FAIL';
export const PRODUCTS_CREATE_RESET = 'PRODUCTS_CREATE_RESET';

export const PRODUCTS_UPDATE_REQ = 'PRODUCTS_UPDATE_REQ';
export const PRODUCTS_UPDATE_SUCC = 'PRODUCTS_UPDATE_SUCC';
export const PRODUCTS_UPDATE_FAIL = 'PRODUCTS_UPDATE_FAIL';
export const PRODUCTS_UPDATE_RESET = 'PRODUCTS_UPDATE_RESET';

export const TEST_PRODUCTS_LIST_REQ = 'TEST_PRODUCTS_LIST_REQ';
export const TEST_PRODUCTS_LIST_SUCC = 'TEST_PRODUCTS_LIST_SUCC';
export const TEST_PRODUCTS_LIST_FAIL = 'TEST_PRODUCTS_LIST_FAIL';

export const TEST_PRODUCTS_DET_REQ = 'TEST_PRODUCTS_DET_REQ';
export const TEST_PRODUCTS_DET_SUCC = 'TEST_PRODUCTS_DET_SUCC';
export const TEST_PRODUCTS_DET_FAIL = 'TEST_PRODUCTS_DET_FAIL';

export const TEST_PRODUCTS_DELETE_REQ = 'TEST_PRODUCTS_DELETE_REQ';
export const TEST_PRODUCTS_DELETE_SUCC = 'TEST_PRODUCTS_DELETE_SUCC';
export const TEST_PRODUCTS_DELETE_FAIL = 'TEST_PRODUCTS_DELETE_FAIL';

export const TEST_PRODUCTS_CREATE_REQ = 'TEST_PRODUCTS_CREATE_REQ';
export const TEST_PRODUCTS_CREATE_SUCC = 'TEST_PRODUCTS_CREATE_SUCC';
export const TEST_PRODUCTS_CREATE_FAIL = 'TEST_PRODUCTS_CREATE_FAIL';
export const TEST_PRODUCTS_CREATE_RESET = 'TEST_PRODUCTS_CREATE_RESET';

export const TEST_PRODUCTS_UPDATE_REQ = 'TEST_PRODUCTS_UPDATE_REQ';
export const TEST_PRODUCTS_UPDATE_SUCC = 'TEST_PRODUCTS_UPDATE_SUCC';
export const TEST_PRODUCTS_UPDATE_FAIL = 'TEST_PRODUCTS_UPDATE_FAIL';
export const TEST_PRODUCTS_UPDATE_RESET = 'TEST_PRODUCTS_UPDATE_RESET';

export const CART_ADD = 'CART_ADD';
export const CART_REMOVE = 'CART_REMOVE';
export const CART_CHANGE = 'CART_CHANGE';
export const CART_SAVE_ADDRESS = 'CART_SAVE_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const LOGIN_REQ = 'LOGIN_REQ'
export const LOGIN_SUC = 'LOGIN_SUC'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_REQ = 'LOGOUT_REQ'

export const REG_REQ = 'REG_REQ'
export const REG_SUC = 'REG_SUC'
export const REG_FAIL = 'REG_FAIL'

export const USER_PROFILE_REQ = 'USER_PROFILE_REQ'
export const USER_PROFILE_SUC = 'USER_PROFILE_SUC'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USERS_REQ = 'USERS_REQ'
export const USERS_SUC = 'USERS_SUC'
export const USERS_FAIL = 'USERS_FAIL'
export const USERS_RESET = 'USERS_RESET'

export const USER_PROFILE_UPD_REQ = 'USER_PROFILE_UPD_REQ'
export const USER_PROFILE_UPD_SUC = 'USER_PROFILE_UPD_SUC'
export const USER_PROFILE_UPD_FAIL = 'USER_PROFILE_UPD_FAIL'
export const USER_PROFILE_UPD_RESET = 'USER_PROFILE_UPD_RESET'

export const ORDER_ADD_REQ = 'ORDER_ADD_REQ'
export const ORDER_ADD_SUC = 'ORDER_ADD_SUC'
export const ORDER_ADD_FAIL = 'ORDER_ADD_FAIL'
export const ORDER_ADD_RESET = 'ORDER_ADD_RESET'

export const ORDER_DET_REQ = 'ORDER_DET_REQ'
export const ORDER_DET_SUC = 'ORDER_DET_SUC'
export const ORDER_DET_FAIL = 'ORDER_DET_FAIL'


export const ORDERS_REQ = 'ORDERS_REQ'
export const ORDERS_SUC = 'ORDERS_SUC'
export const ORDERS_FAIL = 'ORDERS_FAIL'

export const USER_ORDERS_REQ = 'USER_ORDERS_REQ'
export const USER_ORDERS_SUC = 'USER_ORDERS_SUC'
export const USER_ORDERS_FAIL = 'USER_ORDERS_FAIL'

export const ORDER_PAY_REQ = 'ORDER_PAY_REQ'
export const ORDER_PAY_SUC = 'ORDER_PAY_SUC'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

