export const PRODUCTS_LIST_REQ = 'PRODUCTS_LIST_REQ';
export const PRODUCTS_LIST_SUCC = 'PRODUCTS_LIST_SUCC';
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL';

export const PRODUCTS_DET_REQ = 'PRODUCTS_DET_REQ';
export const PRODUCTS_DET_SUCC = 'PRODUCTS_DET_SUCC';
export const PRODUCTS_DET_FAIL = 'PRODUCTS_DET_FAIL';

export const TEST_PRODUCTS_LIST_REQ = 'TEST_PRODUCTS_LIST_REQ';
export const TEST_PRODUCTS_LIST_SUCC = 'TEST_PRODUCTS_LIST_SUCC';
export const TEST_PRODUCTS_LIST_FAIL = 'TEST_PRODUCTS_LIST_FAIL';

export const TEST_PRODUCTS_DET_REQ = 'TEST_PRODUCTS_DET_REQ';
export const TEST_PRODUCTS_DET_SUCC = 'TEST_PRODUCTS_DET_SUCC';
export const TEST_PRODUCTS_DET_FAIL = 'TEST_PRODUCTS_DET_FAIL';

export const CART_ADD = 'CART_ADD';
export const CART_REMOVE = 'CART_REMOVE';
export const CART_CHANGE = 'CART_CHANGE';

export const LOGIN_REQ = 'LOGIN_REQ'
export const LOGIN_SUC = 'LOGIN_SUC'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const REG_REQ = 'REG_REQ'
export const REG_SUC = 'REG_SUC'
export const REG_FAIL = 'REG_FAIL'